name: CI - Build

# Esteira de CI/CD para o Vercel
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build --if-present

  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Obter informações do ambiente Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir artefatos do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Fazer deploy dos artefatos para o Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
